### ISSUE TITLE
Method names inconsistent with function

### ISSUE THREAD

**Issue by XedinUnknown** [Chrico/wp-fields#7]
## The Problem
Method names such as [`ElementInterface#withAttribute()`][] return the same instance. This makes them nothing more than a setter. However, a setter would be named e.g. `setAttribute()`. Names such as `withAttribute()` may mislead the consumer to think that it would return a new instance. Alas, they are simply mutable, and mutability is a bad thing most of the time.

The problem is further enhanced by the fact that these methods do not declare what they return.

## Suggested Solution
Have the methods return a new instance every time, and declare the return type everywhere, including the interface. [Example][1]:

```php
class Element implements
    ElementInterface,
    LabelAwareInterface,
    ErrorAwareInterface,
    DescriptionAwareInterface
{
  	// ...
	
	/**
	 * Creates a new element with the specified attribute value.
	 *
     * @param string $key The attribute key.
     * @param bool|int|string $value The attribute value/
     *
     * @return Element The new element which has the given value of the specified attribute.
     */
    public function withAttribute(string $key, $value): ElementInterface
    {
		$element = clone $this;
        $element->attributes[$key] = $value;

        return $element;
    }

  	// ...
}
```

[1]: https://github.com/Chrico/wp-fields/blob/master/src/Element/Element.php#L53
[`ElementInterface#withAttribute()`]: https://github.com/Chrico/wp-fields/blob/master/src/Element/ElementInterface.php#L71

**Comment by Chrico** [comment]
Thanks for your feedback.

Actually it is absolutly wanted, that an `Element` is mutable, since they are more or less configuration objects. So i would say: This time it's not a bad thing. ;-)

An `Element` should be used like this:

```php
<?php
use ChriCo\Fields\Element\Element;

$textInput = (new Element( 'my-text' ))
	->withAttributes( [ 'type' => 'text'] )
	->withValue('foo')
	->withDescription('This is foo')
	->withLabel('my text input label')
	->withLabelAttributes(['class' => 'foo-label'])
	->withError(['some-id' => 'something went wrong']);
```

There is no need to `clone` and return a copy of the current `Element`, since it's actually wanted that the current object is mutated.

About the `setValue` vs `withValue` - this can be a long discussion i guess, but i decided to use `withValue()` as setter and returning the current object to allow chaining for configuration of an `Element`. By using `setValue()`, i would probably not allow to chain. 
Also, as getter i'm just using e.G. `value()` instead of `getValue()`. 

This is a design decision i made for the 1.x version. And i cannot simply change it without a major release.

**Comment by XedinUnknown** [comment]
Thanks for the quick reply!

Why would you actually _want_ the object to be mutable? It's perfectly possible and normal to chain calls to `with*()` configuration methods if you return a new instance every time: [FIG is doing that][1] no problem. Same thing with `setValue()`:

```php
$textInput = (new Element('my-text'))
	->setAttributes(['type' => 'text'])
	->setValue('foo')
	->setDescription('This is foo');
```

Of course, I would much prefer that the methods are called `withAttributes()` etc, but it would be great and much more intuitive if they returned a new instance every time.

[1]: https://www.php-fig.org/psr/psr-7/#headers-with-multiple-values

**Comment by XedinUnknown** [comment]
Hi! Any news on this? :)

**Comment by Chrico** [comment]
yes, i'll not change the whole API in version 1.x :)

**Comment by XedinUnknown** [comment]
Well, I'm not saying you should change it in any specific version, just that it could be a good idea to do it eventually. What do you think?
